services:
  vue-build:
    image: node:22.14.0-slim
    container_name: vue-build
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/dist:/app/frontend/dist
    command: |
      sh -c "npm install && npm run build"
    depends_on:
      - web
  web:
    build: .
    container_name: app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - 8000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - DEBUG=0
  
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - web
  
  postgres:
    image: postgres:17.4
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:7.4.2
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default  

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  static_volume: